### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m1-evaluacion-intermedia-samanthacancino#1]
Really cool job @samanthacancino  !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Fix the language and the meta title of the page
- [x] Logo should be out of nav
- [x] We need h1 tag
- [x] Remove styles from HTML https://github.com/Adalab/m1-evaluacion-intermedia-samanthacancino/blob/master/index.html#L17

## CSS - structure
- [x] Move the font CSS before your main CSS

## CSS - selectors
- [x] Class selectors are free, let's use them instead tag selectors 

## CSS - box model
- [x] Instead of adding extra space at the bottom of the header, you can make the menu links taller, that would make the header be tall enough and also would make the link easier to touch on mobile devices ;)
- [x] Fix the main area, you have an extra white space at the bottom
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)

## CSS - flex
- [x] Main title should be vertically and horizontally centered (should we use Flex to achieve this?)

## CSS - other
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Remove commented CSS rules

## Assets
- [x] Use relative routes like `./styles/main.css`.

## Good practices
- [x] Indent and avoid extra white spaces to improve readability and avoid bugs
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text
- [x] Organize your files in folders, you have a guide to help you with that here --> https:## books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto
- [x] Add .gitignore to omit .DS_Store folders
- [ ] Finish the exercise

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with main content.

## Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
Falta mejorar alguna cosilla y finalizar el ejercicio, pero en general buen trabajo.

![Good job](https://media.giphy.com/media/Xl6MM0lOHGkSY/giphy.gif)

**Comment by samanthacancino** [comment]
Gracias Miguel, me pongo a ello :)

**Comment by migueldelmazo** [comment]
Gracias por hacer las mejoras que os hemos pedido!!!
